INSERT INTO "tags" ("id","nom","id_categorie","tags_osm")
VALUES
(1,'Boutiques',1,'shop=boutique'),
(2,'Brocante',1,'shop=department_store'),
(3,'Supermarché',1,'shop=supermarket'),
(4,'Epicerie',1,'shop=convenience'),
(5,'Blanchisseries et Pressings',1,'amenity=washing_machine'),
(6,'Centre Commercial',1,NULL),
(7,'Maison et Jardin',1,'landuse=allotmentsrg'),
(8,'Hifi, téléphonie',1,'amenity=telephone'),
(9,'Fleuriste',1,'shop=florist'),
(10,'Boulangerie, Pâtisserie',1,'shop=bakery'),
(11,'Caviste',1,NULL),
(12,'Tabac',1,'shop=cannabis'),
(13,'Jouets et jeux',1,'shop=toy'),
(14,'Magasin de sport',1,'shop=sport'),
(15,'Ameublement et Mobilier',1,'office=estate_agent'),
(16,'Fournitures de Bureaux',1,'shop=stationery'),
(17,'Mobilier de Bureaux',1,'shop=stationery'),
(18,'Mobilier de Jardin',1,'leisure=garden'),
(19,'Vêtements',1,'shop=clothes'),
(20,'Chaussures',1,'shop=shoes'),
(21,'Bijoux et accessoires',1,'shop=fashion_accessories'),
(22,'Puériculture',1,NULL),
(23,'Administrations',2,'office=government'),
(24,'Ambassades et Consulats',2,'diplomatic=embassy'),
(25,'Associations, syndicats',2,'office=association'),
(26,'Douane, Agences',2,NULL),
(27,'Ministères',2,NULL),
(28,'O.N.G &amp; Organisations Internationales',2,'office=ngo'),
(29,'Offices Nationaux',2,'office=government'),
(30,'Poste',2,'amenity=post_office'),
(31,'Sécurité Sociale',2,'amenity=social_facility'),
(32,'Institution publique',2,'office=government'),
(33,'Matériels et Produits agricoles',3,'building=barn;craft=agricultural_engines'),
(34,'Agricole, Produits Chimiques',3,'building=barn'),
(35,'Agriculture',3,'building=barn'),
(36,'Equipements et Matériel agricoles',3,'building=barn;craft=agricultural_engines'),
(37,'Agro-Alimentaire',3,NULL),
(38,'Agro-Industrie',3,NULL),
(39,'Elevage',3,'amenity=animal_breeding'),
(40,'Elevage - Consultants',3,'amenity=animal_breeding'),
(41,'Abattoirs et Viande en Gros',4,NULL),
(42,'Alcools, vins, spiritueux, drogueries',4,'amenity=bar;shop=alcohol'),
(43,'Alimentaire, Distributeurs et Grossistes',4,NULL),
(44,'Industries alimentaires',4,'landuse=industrial'),
(45,'Produits alimentaires',4,NULL),
(46,'Alimentation Animale',4,NULL),
(47,'Alimentation Générale',4,NULL),
(48,'Boissons',4,'craft=brewery;amenity=bar'),
(49,'Boucherie - charcuterie',4,NULL),
(50,'Boulangeries, Patisseries, Glaces',4,'shop=bakery'),
(51,'Boulangeries, Patisseries, Glaces - matériel &amp; équipement',4,'shop=bakery'),
(52,'Brasseries',4,'craft=brewery'),
(53,'Brasseries - matériel &amp; équipement',4,'craft=brewery'),
(54,'Cacao - Production et Exportation',4,'highway=track;landuse=farm'),
(55,'Café - Production et Exportation',4,'highway=track;landuse=farm'),
(56,'Catering',4,'amenity=caterer'),
(57,'Distilleries',4,'craft=distillery'),
(58,'Environnement',4,'amenity=area'),
(59,'Gomme Arabique',4,NULL),
(60,'Lait, Yaourt et Fromage',4,'shop=cheese'),
(61,'Laiteries',4,'vending=milk'),
(62,'Minoteries',4,NULL),
(63,'Pêche - Commercialisation et Exportation',4,'vending=fishing_bait;leisure=fishing'),
(64,'Pêche - Congelation',4,'vending=fishing_bait'),
(65,'Sucre, Fabrication et Raffinage',4,NULL),
(66,'Supermarchés',4,'shop=supermarket'),
(67,'Thé - Production et Commercialisation',4,NULL),
(68,'Traiteurs',4,'amenity=caterer'),
(69,'Auto-Ecoles',5,'amenity=driving_school'),
(70,'Automobiles et Concessionnaires',5,'shop=car_repair'),
(71,'Expertises automobiles',5,'shop=car_repair'),
(72,'Automobiles - Pièces Détachées et Accessoires',5,'shop=car_parts'),
(73,'Voitures d''occasion',5,'shop=second_hand'),
(74,'Constructions Mécaniques',5,NULL),
(75,'Contrôles Techniques',5,'amenity=vehicle_inspection'),
(76,'Cycles et Motos',5,'actuator=electric_motor'),
(77,'Engins de Chantier et Matériels',5,NULL),
(78,'Garages',5,'amenity=car_rental'),
(79,'Mécanique Générale',5,NULL),
(80,'Mécanique - Industries',5,'landuse=industrial'),
(81,'Moteurs et Pompes',5,NULL),
(82,'Pneumatiques',5,'actuator=pneumatic_cylinder'),
(83,'Tracking',5,'cycleway=track'),
(84,'Véhicules Industriels',5,'cycleway=track'),
(85,'Station-service',5,NULL),
(86,'Parking',5,'amenity=parking'),
(87,'Garage',5,'building=garage'),
(88,'Assurances',6,'office=insurance'),
(89,'Assurances Vies',6,'office=insurance'),
(90,'Assurances médicales',6,'office=insurance'),
(91,'Assureurs - Courtiers Et Conseils',6,'office=insurance'),
(92,'Banques et Organismes Financiers',6,'amenity=bank'),
(93,'Equipements de Sécurité Bancaire',6,'amenity=bank'),
(94,'Banques - Services Mobiles',6,'amenity=bank'),
(95,'Bureaux de Change et Transferts d''argent',6,'amenity=bureau_de_change'),
(96,'Bureaux de Contrôle',6,NULL),
(97,'Cabinets Comptables',6,NULL),
(98,'Centres d''Information',6,'information=office'),
(99,'Crédits et Finances',6,NULL),
(100,'Enquêtes, recherches et investigation',6,NULL),
(101,'Holdings',6,NULL),
(102,'Investissements',6,NULL),
(103,'Transports de Fonds',6,NULL),
(104,'Adduction d''eau et VRD',7,NULL),
(105,'Agencement et Décoration',7,NULL),
(106,'Industrie d''aluminium',7,NULL),
(107,'Aménagement des Terrains Urbains',7,NULL),
(108,'Architecture et Urbanisme',7,NULL),
(109,'Ascenseurs',7,NULL),
(110,'Assainissement et Canalisations',7,NULL),
(111,'Bâches et Stores',7,'outlet=noise_barrier'),
(112,'Bâtiments et Travaux Publics',7,'building=yes'),
(113,'Bâtiments - Expertises',7,'building=yes'),
(114,'Bâtiments - Nettoyage',7,'building=yes'),
(115,'Bâtiments - Préfabriqué',7,'building=yes'),
(116,'Bâtiments - Ravalement',7,'building=yes'),
(117,'Bâtiments - Réhabilitation',7,'building=yes'),
(118,'Bâtiments - Second Œuvre',7,'building=yes'),
(119,'Bitume',7,NULL),
(120,'Bois et Négoce',7,'craft=carpenter'),
(121,'Bois - Industries',7,'craft=carpenter;shop=hardware;landuse=industrial'),
(122,'Bois - Scieries',7,'craft=carpenter;shop=hardware'),
(123,'Bricolage',7,'shop=doityourself'),
(124,'Briqueteries',7,NULL),
(125,'Bureaux d''Etudes et D''Ingénierie',7,NULL),
(126,'Câbles',7,NULL),
(127,'Caoutchouc',7,NULL),
(128,'Carrelages',7,NULL),
(129,'Carrières - Exploitations et Exploration',7,NULL),
(130,'Chaudronnerie',7,NULL),
(131,'Cimenteries',7,NULL),
(132,'Citernes - Métallique et Plastique',7,NULL),
(133,'Climatisation',7,NULL),
(134,'Climatisation - Dépannage et Maintenance',7,NULL),
(135,'Constructions Industrielles',7,NULL),
(136,'Constructions Métalliques',7,NULL),
(137,'Développement Rural et Urbain',7,NULL),
(138,'Ebenistes',7,NULL),
(139,'Echafaudages',7,NULL),
(140,'Espaces Verts et Jardins',7,NULL),
(141,'Etanchéité',7,NULL),
(142,'Faux-Plafonds et Staff',7,NULL),
(143,'Fer et Acier',7,NULL),
(144,'Forages',7,'man_made=water_well'),
(145,'Forages - Maintenance',7,'man_made=water_works'),
(146,'Forages - Matériels et Equipements',7,'man_made=wastewater_plant'),
(147,'Forestiers - Matériels et Equipement',7,NULL),
(148,'Génie Civil',7,NULL),
(149,'Géologues',7,NULL),
(150,'Géomètres - topographes',7,NULL),
(151,'Groupes Electrogènes',7,NULL),
(152,'Hydraulique',7,'actuator=hydraulic_cylinder'),
(153,'Hydraulique - Constructions',7,'actuator=hydraulic_cylinder'),
(154,'Hydraulique - Matériels et Equipements',7,'actuator=hydraulic_cylinder'),
(155,'Isolation industrielle',7,'landuse=industrial'),
(156,'Laboratoires d''Analyses du Bâtiment',7,NULL),
(157,'Location d''Engins de Chantier',7,NULL),
(158,'Matériaux de Construction',7,NULL),
(159,'Menuiseries Aluminium',7,'craft=joiner;craft=carpenter;craft=cabinet_maker'),
(160,'Menuiseries Bois',7,'craft=joiner;craft=carpenter;craft=cabinet_maker'),
(161,'Menuiseries Industrielles',7,'craft=joiner;craft=carpenter;craft=cabinet_maker'),
(162,'Menuiseries Métalliques',7,'craft=joiner;craft=carpenter;craft=cabinet_maker'),
(163,'Mines - Exploitations et Exploration',7,NULL),
(164,'Mines - Import et Export',7,NULL),
(165,'Mines - Matériels et Equipements',7,NULL),
(166,'Mines - Recherche',7,NULL),
(167,'Miroiteries et Vitreries',7,NULL),
(168,'Ouvrages d''Art',7,NULL),
(169,'Peintres',7,'craft=painter'),
(170,'Peinture',7,'craft=painter'),
(171,'Piscines',7,'leisure=swimming_pool'),
(172,'Plomberie et Sanitaires',7,'craft=plumber;craft=hvac'),
(173,'Portes et Fenêtres',7,'craft=window_construction'),
(174,'Propreté urbaine',7,NULL),
(175,'Quincailleries',7,NULL),
(176,'Routes',7,'highway=trunk;highway=secondary;type=route'),
(177,'Routes - Matériaux',7,'highway=trunk;highway=secondary;type=route'),
(178,'Routes - Signalisation',7,'highway=trunk;highway=secondary;type=route'),
(179,'Serrureries',7,'craft=locksmith'),
(180,'Toitures - Matériaux',7,NULL),
(181,'Tôles',7,NULL),
(182,'Topographie',7,NULL),
(183,'Travaux Publics et Terrassement',7,NULL),
(184,'Travaux Publics et Terrassement - Maintenance',7,NULL),
(185,'Tuyauteries et PVC',7,NULL),
(186,'Coiffeur',8,'shop=hairdresser'),
(187,'Institut de beauté, parfumerie, relaxation',8,'shop=beauty'),
(188,'Massages',8,'shop=massage'),
(189,'Centrales d''Achats',9,NULL),
(190,'Chambres de Commerce',9,NULL),
(191,'Commerce Exterieur - Promotion',9,NULL),
(192,'Commerce Général',9,NULL),
(193,'E-Commerce',9,NULL),
(194,'Groupements D''Entreprises',9,NULL),
(195,'Import et Export',9,NULL),
(196,'Promotion Commerciale et Etudes',9,NULL),
(197,'Recouvrements Commerciaux',9,NULL),
(198,'Représentation Commerciale',9,NULL),
(199,'Agences de Mannequins',10,NULL),
(200,'Agences de Presse et d''Information',10,'office=publisher'),
(201,'Agences de Publicité et de Communication',10,'office=advertising_agency'),
(202,'Audiovisuel - Matériels et Production',10,NULL),
(203,'Evénementiel',10,'amenity=community_centre;amenity=events_venue'),
(204,'Journaux et Presse',10,'office=newspaper'),
(205,'Maison d''édition',10,'office=publisher'),
(206,'Marketing',10,'office=advertising_agency'),
(207,'Objets Publicitaires',10,'advertising=sculpture'),
(208,'Organisations de Conférences',10,NULL),
(209,'Radio et Télévision',10,NULL),
(210,'Radio-Communication',10,NULL),
(211,'Relations Publiques et Organisations',10,NULL),
(212,'Ressources Humaines',10,NULL),
(213,'Sérigraphie',10,NULL),
(214,'Eau - Distribution',11,'vending=water'),
(215,'Eau - Laboratoires d''Analyses',11,'landuse=pond'),
(216,'Eau - Traitement',11,'landuse=pond'),
(217,'Centres de Documentation',12,NULL),
(218,'Crèche',12,'amenity=kindgarten;amenity=childcare'),
(219,'Centre de loisirs d''enfants',12,NULL),
(220,'Centre linguistique - enseignement',12,NULL),
(221,'Centres de Formation',12,NULL),
(222,'Centres de Recherche',12,NULL),
(223,'Ecoles et Universités',12,'amenity=college'),
(224,'Automatisme',13,NULL),
(225,'Batteries et Piles',13,NULL),
(226,'Electricité - Générale et Industrielle',13,'craft=electronics_repair'),
(227,'Electricité - Expertises',13,'craft=electrician'),
(228,'Electricité - Industries',13,'craft=electronics_repair'),
(229,'Electricité - Ingénierie',13,'craft=electrician'),
(230,'Electricité - Materiels et Equipement',13,'craft=electronics_repair'),
(231,'Electrification Rurale Et Urbaine',13,NULL),
(232,'Electromécanique',13,NULL),
(233,'Energie',13,'power=station;power=generator'),
(234,'Energie Nouvelle et Renouvelable',13,'power=plant'),
(235,'Energie Solaire',13,NULL),
(236,'Gaz Domestique Et Industriel',13,NULL),
(237,'Géotechnique',13,NULL),
(238,'Hydrocarbures - Aviation',14,NULL),
(239,'Hydrocarbures - Distribution',14,NULL),
(240,'Hydrocarbures - Equipements Et Mater...',14,NULL),
(241,'Hydrocarbures - Expertises',14,NULL),
(242,'Hydrocarbures - Exploration',14,NULL),
(243,'Hydrocarbures - Logistiques',14,NULL),
(244,'Hydrocarbures - Lubrifiants',14,NULL),
(245,'Hydrocarbures - Maintenance',14,NULL),
(246,'Hydrocarbures - Production',14,NULL),
(247,'Hydrocarbures - Transports',14,NULL),
(248,'Pétroliers, Constructions',14,NULL),
(249,'Pétroliers - Matériels et Equipement',14,NULL),
(250,'Raffineries',14,NULL),
(251,'Garde Meubles',15,NULL),
(252,'Immobilier - Agences',15,'office=estate_agent'),
(253,'Immobilier - Expertises',15,NULL),
(254,'Immobilier - Gestion',15,NULL),
(255,'Immobilier - Location',15,NULL),
(256,'Immobilier - Promoteurs',15,NULL),
(257,'Electro-Ménager',16,NULL),
(258,'Electronique',16,NULL),
(259,'Allumettes et Bougies',16,NULL),
(260,'Armes et Munitions',16,'shop=military_surplus'),
(261,'Assistance Technique',16,NULL),
(262,'Cartonneries',16,NULL),
(263,'Chaussures, Manufactures',16,'shop=shoes'),
(264,'Coton',16,NULL),
(265,'Dépannage et Maintenance Industrielle',16,NULL),
(266,'Diamant et Or',16,NULL),
(267,'Emballage et Conditionnement',16,NULL),
(268,'Equipements de Bureaux',16,'shop=stationery'),
(269,'Equipements Industriels',16,NULL),
(270,'Fournitures Industrielles',16,'shop=furniture'),
(271,'Froid Industriel',16,NULL),
(272,'Location De Matériels',16,NULL),
(273,'Machines-Outils, Manufactures',16,NULL),
(274,'Manutention Industrielle',16,NULL),
(275,'Matelas',16,'shop=bed'),
(276,'Matelas, Equipements et Materiels',16,'shop=bed'),
(277,'Mesure et Pesage, Materiels',16,NULL),
(278,'Nettoyage Industriel',16,NULL),
(279,'Nettoyage, Matériels et Equipements',16,NULL),
(280,'Papier - Industries',16,'landuse=industrial'),
(281,'Pièces Détachées Industrielles',16,'landuse=industrial'),
(282,'Plastique - Industries',16,'landuse=industrial'),
(283,'Plastique - Produits',16,NULL),
(284,'Savonneries',16,NULL),
(285,'Soudage, Matériels et Produits',16,'craft=welder'),
(286,'Tabac, Manufactures et Importateurs',16,'shop=cannabis'),
(287,'Travail Temporaire, Interim',16,NULL),
(288,'Tuyauteries',16,NULL),
(289,'Verre - Industries',16,NULL),
(290,'Zone Franche Industrielle',16,'landuse=industrial'),
(291,'Ameublement et Mobilier, Industries',16,NULL),
(292,'Fournitures de Bureaux, Industries',16,'shop=stationery'),
(293,'Mobilier - Industries',16,NULL),
(294,'Chimie - Industries',16,NULL),
(295,'Chimie - Produits',16,NULL),
(296,'Parfum, Industries',16,'shop=beauty'),
(297,'Antennes Paraboliques, Equipements',17,NULL),
(298,'Archivage Numerique',17,NULL),
(299,'Bureautique',17,NULL),
(300,'Business Center',17,NULL),
(301,'Centres d''Appels',17,NULL),
(302,'Courriers Express, Colis Express',17,NULL),
(303,'Cyber-Cafes',17,NULL),
(304,'Domiciliation de Sociétés',17,NULL),
(305,'Editeurs',17,'office=newspaper'),
(306,'Etudes de Marchés',17,NULL),
(307,'Imprimeries',17,'shop=copyshop;craft=printer'),
(308,'Imprimeries, Matériels et Equipement',17,'shop=copyshop'),
(309,'Informatique',17,NULL),
(310,'Informatique - Consommables',17,NULL),
(311,'Informatique - Constructeurs',17,NULL),
(312,'Informatique - Consultants',17,NULL),
(313,'Informatique - Environnement',17,NULL),
(314,'Informatique - Expertises',17,NULL),
(315,'Informatique - Gestion De Maintenance',17,NULL),
(316,'Informatique - Ingénierie',17,NULL),
(317,'Informatique - Ingénieurs',17,NULL),
(318,'Informatique - Maintenance',17,NULL),
(319,'Informatique - Reseaux',17,NULL),
(320,'Informatique - Securite',17,NULL),
(321,'Internet',17,NULL),
(322,'Internet - Provider',17,NULL),
(323,'Internet - Web Design',17,NULL),
(324,'Internet - E-Business &amp; E-Commerce',17,NULL),
(325,'Paratonnerre',17,NULL),
(326,'Technologies Nouvelles',17,NULL),
(327,'Technologies Nouvelles, Consultants',17,NULL),
(328,'Traducteurs Et Interpretes',17,NULL),
(329,'Avocats',18,NULL),
(330,'Avocats d''Affaires Internationales',18,NULL),
(331,'Cabinets Juridiques et Fiscaux',18,NULL),
(332,'Consultants',18,NULL),
(333,'Consultants en Immigration',18,NULL),
(334,'Consultants Internationaux',18,NULL),
(335,'Expertises Comptables, Audit Et Conseil',18,NULL),
(336,'Expertises - Etudes, Communication',18,NULL),
(337,'Expertises Judiciaire',18,NULL),
(338,'Huissiers De Justice',18,NULL),
(339,'Notaires',18,NULL),
(340,'Projets et Bureaux D''Appui',18,NULL),
(341,'Artisanat, Antiquaires et Galeries d''Art',19,NULL),
(342,'Cadeaux',19,NULL),
(343,'Casino',19,'amenity=casino'),
(344,'Cinéma et vidéothèques',19,'amenity=cinema'),
(345,'Centre culturel',19,'landuse=recreation_ground'),
(346,'Musée',19,'tourism=museum'),
(347,'Musique',19,'leisure=bandstand'),
(348,'Théâtre, spectacle',19,'amenity=theatre'),
(349,'Cabaret',19,'leisure=dance'),
(350,'Bibliothèque et Centre de Documentation',19,'amenity=library'),
(351,'Librairie, papeterie',19,'amenity=library'),
(352,'Sport',19,'building=pavilion;club=sport;leisure=fitness_centre'),
(353,'Espaces verts et Jardins',19,'leisure=park'),
(354,'Salle de spectacles - salle de fêtes',19,NULL),
(355,'Loisirs, jeux et entertainment',19,'leisure=playground'),
(356,'Loterie',19,'amenity=lottery'),
(357,'Voyance, Medium',19,NULL),
(358,'Restaurant',20,'amenity=restaurant'),
(359,'Night Clubs et Discothèques',20,'amenity=nightclub'),
(360,'Restauration rapide',20,'amenity=fast_food'),
(361,'Bar, Café',20,'amenity=bar;amenity=cafe'),
(362,'Salons de Thé et Glaciers',20,'shop=ice_cream'),
(363,'Ambulance',21,'emergency=ambulance_station'),
(364,'Assistance sociale',21,'amenity=social_facility'),
(365,'Médecine Générale',21,'amenity=doctors'),
(366,'Médecine Spécialisée - dentiste',21,'amenity=dentist'),
(367,'Médecine Spécialisée - dermatologie',21,'amenity=doctors'),
(368,'Médecine Spécialisée - cardiologie',21,'amenity=doctors'),
(369,'Médecine Spécialisée - oncologie',21,'amenity=doctors'),
(370,'Médecine Spécialisée - ophtalmologie',21,'amenity=doctors'),
(371,'Médecine Spécialisée - psychologie',21,'amenity=doctors'),
(372,'Médecine Spécialisée - angiologie',21,'amenity=doctors'),
(373,'Médecine Spécialisée - pédicure et podologie',21,'amenity=doctors'),
(374,'Médecine Spécialisée - ostéopathie',21,'amenity=doctors'),
(375,'Médecine Spécialisée - gynécologie',21,'amenity=doctors'),
(376,'Médecine Spécialisée - kinésithérapeute',21,'amenity=doctors'),
(377,'Médecine naturelle, traditionnelle',21,'amenity=doctors'),
(378,'Médecine du travail',21,NULL),
(379,'Chirurgie',21,'amenity=doctors'),
(380,'Chirurgie Esthétique',21,NULL),
(381,'Cliniques et Hopitaux',21,'amenity=clinic;amenity=hospital;amenity=healthcare'),
(382,'Cosmétiques - Industries',21,'shop=beauty'),
(383,'Cosmétiques - Produits',21,'shop=beauty'),
(384,'Drogueries',21,'shop=cannabis'),
(385,'Laboratoires d''Analyses Médicales',21,NULL),
(386,'Laboratoires, Matériels et Equipement',21,NULL),
(387,'Laboratoires - Produits',21,NULL),
(388,'Medical - Assistance',21,'shop=medical_supply'),
(389,'Medical - Gaz Medical',21,'shop=medical_supply'),
(390,'Medical - Industries',21,'shop=medical_supply'),
(391,'Medical - Materiels Et Equipements',21,'shop=medical_supply'),
(392,'Medical - Produits',21,'shop=medical_supply'),
(393,'Opticiens',21,'craft=optician'),
(394,'Opticiens - Matériels et Equipements',21,'craft=optician'),
(395,'Para-Pharmacie',21,'amenity=pharmacy'),
(396,'Pharmaceutiques - Distributeurs',21,'amenity=pharmacy'),
(397,'Pharmaceutiques - Industries',21,'amenity=pharmacy'),
(398,'Pharmaceutiques - Laboratoires',21,'amenity=pharmacy'),
(399,'Pharmaceutiques - Materiels Et Equipement',21,'amenity=pharmacy'),
(400,'Pharmaceutiques - Produits',21,'amenity=pharmacy'),
(401,'Pharmacies',21,'amenity=pharmacy'),
(402,'Phytosanitaires - Traitements',21,NULL),
(403,'Urgences Medicales',21,'emergency=ambulance_station'),
(404,'Vétérinaires',21,'amenity=veterinary'),
(405,'Vétérinaires, Produits et Pharmacie',21,NULL),
(406,'Alarmes Et Surveillance, Matériels électroniques',22,NULL),
(407,'Badges, Fabrication',22,NULL),
(408,'Controles Techniques',22,'amenity=vehicule_inspection'),
(409,'Détectives',22,NULL),
(410,'Escorte Véhicules',22,NULL),
(411,'Gardiennage et Sécurité',22,NULL),
(412,'Gardiennage et Sécurité - Equipements',22,NULL),
(413,'Incendie et Protection - Matériels',22,'amenity=fire_station'),
(414,'Sécurité - Audits et Consultants',22,NULL),
(415,'Télé-Surveillance et Vidéo-Surveillance',22,'utility=telecom'),
(416,'Télécommunications - Transmission de signal',23,'utility=telecom;telecom=service_device'),
(417,'Télécommunications et Téléphonie',23,'shop=mobile_phone;utility=telecom;telecom=service_device'),
(418,'Télécommunications - Fibres Optique',23,'utility=telecom;telecom=service_device'),
(419,'Télécommunications - Installation et maintenance',23,'utility=telecom;telecom=service_device'),
(420,'Télécommunications - Matériels et équipement',23,'utility=telecom;telecom=service_device'),
(421,'Télécommunications - Mobiles',23,'shop=mobile_phone;utility=telecom;telecom=service_device'),
(422,'Télécommunications - Réseaux',23,'utility=telecom;telecom=service_device'),
(423,'Télécommunications - Satellite',23,'utility=telecom;telecom=service_device'),
(424,'Confection, Couture, Broderie',24,'shop=sewing'),
(425,'Equipements et vêtements militaires',24,'shop=military_surplus'),
(426,'Friperies',24,'shop=clothes'),
(427,'Prêt à Porter - Gros et Détail',24,'shop=clothes'),
(428,'Textile',24,NULL),
(429,'Textile, Filature, Tissage, Impression',24,NULL),
(430,'Textile, Fournitures',24,'shop=furniture'),
(431,'Textile - Matériels et Equipements',24,NULL),
(432,'Vêtements Manufactures',24,NULL),
(433,'Agences de Tourisme',25,'information=office'),
(434,'Centres d''Information',25,'information=office'),
(435,'Agences de voyage, tours opérateurs',25,NULL),
(436,'Equipements Hôtels et Restaurants',25,'tourism=hotel'),
(437,'Hôtel',25,'tourism=hotel'),
(438,'Auberge',25,'tourism=motel'),
(439,'Location d''avions',25,NULL),
(440,'Location de bateaux',25,'amenity=boat_rental;shop=boat'),
(441,'Location de voitures',25,'amenity=car_rental;amenity=car_sharing'),
(442,'Transport Logistique',25,NULL),
(443,'Transports Touristiques',25,'information=office'),
(444,'Accastillage',26,NULL),
(445,'Acconage',26,NULL),
(446,'Aéronautique',26,'building=hangar'),
(447,'Aéronautique - Centrales D''Achats',26,NULL),
(448,'Aéronautique - Maintenance',26,'building=hangar'),
(449,'Aéroports',26,'aeroway=aerodrome'),
(450,'Aéroports - Equipements',26,'aeroway=aerodrome'),
(451,'Aéroports - Maintenance',26,'aeroway=aerodrome'),
(452,'Aéroports - Securite Aerienne',26,'aeroway=aerodrome'),
(453,'Aéroports - Services',26,'aeroway=aerodrome'),
(454,'Agences en Douane',26,NULL),
(455,'Agences Maritimes',26,'amenity=ferry_terminal'),
(456,'Aéronautique - Pièces Détachées',26,NULL),
(457,'Chantiers Navals',26,NULL),
(458,'Chemin de Fer',26,'railway=subway'),
(459,'Compagnies Aériennes',26,NULL),
(460,'Containers, Fabrication et Location',26,NULL),
(461,'Déménagements',26,NULL),
(462,'Expertises Maritimes et Terrestres',26,NULL),
(463,'Fret aérien - maritime &amp; international',26,NULL),
(464,'Manutention et Entreposage',26,NULL),
(465,'Manutention - Equipements',26,NULL),
(466,'Manutention - Portuaire',26,'amenity=ferry_terminal'),
(467,'Ports',26,'amenity=ferry_terminal'),
(468,'Ports, Matériels et Equipements',26,'amenity=ferry_terminal'),
(469,'Shipchandler',26,NULL),
(470,'Transit et Consignation',26,NULL),
(471,'Transports Aériens',26,NULL),
(472,'Transports en Commun',26,'public_transport=platform'),
(473,'Transports Ferroviaires',26,'railway=subway'),
(474,'Transports Internationaux',26,NULL),
(475,'Transports Maritimes',26,'amenity=ferry_terminal'),
(476,'Transports Routiers',26,'route=coach'),
(477,'Transports Urbains',26,'route=coach'),
(478,'Travaux Maritimes',26,'amenity=ferry_terminal');
